// Questions
var q = [
  "What are you working on ?",
  "What problem are you solving?",
  "What are the specific problems of your different user types?",
  "Can you quantify the problem in any way? Time? Money?",
  "What is your value proposition?",
  "What is your product vision?",
  "Where do you see yourself in 5 years?",
  "How are you different from E-Commerce Accelerators?",
  "How are you different from Traditional agencies?",
  "How are you different from Channel syndicators?",
  "What is your tech stack?",
  "Do you have a demo?",
  "Who are your users?",
  "Tell me more about these users",
  "What are the use cases you are seeing?",
  "What is your user growth rate?",
  "What’s next for you?",
  "How are you understanding user needs?",
  "How have you validated your product or service with your target audience?",
  "What has surprised you about user desires?",
  "Can you walk us through a use case?",
  "What did you achieve in the last weeks (Tech)?",
  "What did you achieve in the last weeks (Traction)?",
  "Do you have revenue?",
  "Why don’t you have revenue?",
  "How will you make money?",
  "What is your business model?",
  "Is the market big enough?",
  "What's the TAM?",
  "What stops competitors from completely destroying you?",
  "What do you see that all the other smart people don’t see?",
  "What are the key things about your field that outsiders don’t understand?",
  "Why are you the right team to build this?",
  "What domain expertise do you have?",
  "How do you deal with disagreements in the team? Who makes the final call?",
  "What was the biggest argument between co-founders since you started working together?",
  "How do you handle knowledge gaps in the team?",
  "How do you distribute responsibilities?",
  "What is your team's background?",
  "What’s your demo day goal?",
  "What KPI are you optimizing for?",
  "How do you measure success for your startup?",
  "What milestones do you plan to achieve in the next 6-12 months?",
  "How do you plan to use the funds from Y Combinator to grow your business?",
  "What YC help will you need in the next 3-4 months?",
  "If your startup succeeds what additional areas might you be able to expand into?",
  "Why did you pick this idea to work on and not of the other 100 ideas out there?",
  "What will you do if we don’t fund you?",
  "Are you talking to investors right now?",
  "What is the biggest risk in preventing you from staying on track?",
  "What are the biggest risks or challenges you foresee for your startup?",
  "What's the biggest mistake you have made?",
  "Who would be your next hire?",
  "How long can you go before funding?",
  "Someone just showed us an idea like this right before you guys. I don't like it. What else do you have?",
  "Will you reincorporate as a US company?",
  "Will your team stick at this?",
  "Have you raised funding?",
  "What is your burn rate?",
  "What's the funniest thing that has happened to you?",
  "Would you relocate to Silicon Valley?",
  "Tell us something surprising you have done?",
  "What obstacles will you face and how will you overcome them (Tech)?",
  "What obstacles will you face and how will you overcome them (Business)?",
  "What else have you created together?",
  "What part of your project are you going to build first?",
  "Why will you succeed?",
  "Who is 'the boss'?",
  "What systems have you hacked?",
  "Who are your competitors?",
  "How much money could you make per year?",
  "Who is (going to be) your first paying customer?",
  "What's an impressive thing you have done?",
  "Who might become competitors?",
  "Are you open to changing your idea?",
  "How does your product work in more detail?",
  "How do we know your team will stick together?",
  "Six months from now, what's going to be your biggest problem?",
  "In what ways are you resourceful?",
  "What, exactly, makes you different from existing options?",
  "Where is the rocket science here?",
  "Who in your team does what?",
  "How did your team meet?",
  "How do you know customers need what you’re making?",
  "How will customers and/or users find out about you?",
  "What makes new users try you?",
  "Why do the reluctant users hold back?",
  "What’s new about what you make?",
  "What has surprised you about user behavior?",
  "Are your customers one-and-done, or do they come back?",
  "What are other ways people solve this problem?",
  "Why haven’t you made more progress?",
  "Why is your product priced the way it is?",
  "Why do you want to be part of YC?",
  "How do you think about your ASP (average selling price) over time? Do you think this will go up, down, or stay about the same? Why?",
  "How big is this market, really?",
  "What’s the worst thing that happened?",
  "What’s the biggest mistake you have made?",
  "What problems / hurdles are you anticipating? How will you overcome them?",
  "What will be the biggest challenge two years from now?",
  "Who do you fear the most?",
  "What do you understand that others don’t?",
  "Why isn’t someone already doing this?",
  "How is your product different?",
  "What do you understand about your users?",
  "Won’t [big company] just launch a [whatever your company does] feature and kill you?",
  "What’s an impressive thing you’ve done?",
  "Is it harder to find suppliers to list [whatever good or service], or buyers to buy?",
  "How would it work to expand geographically?",
  "Why is your commission so high?",
  "Why is your commission so low?",
  "How do you all know each other?",
  "Why did your team get together?",
  "What is your growth like?",
  "What’s the conversion rate?",
  "What’s the repeat buyer rate?",
  "What’s the churn rate?",
  "How much does customer acquisition cost?",
  "What is the average price of a [purchase, subscription, etc]?",
  "Why isn't someone already doing this?",
  "How will you get users?",
  "How do you know people want this?",
  "Who needs what you're making?",
  "What do you understand that others don't?",
  "Tell us about a tough problem you solved?",
  "What resistance will they have to trying you and how will you overcome it?",
  "Where do new users come from?",
  "What problems/hurdles are you anticipating?",
  "What competition do you fear most?"
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
